### ISSUE TITLE
USB gigabit adapter do not show up in ostinato port group on windows 7

### ISSUE THREAD

**Issue by ftobiassen** [pstavirs/ostinato#165]
USB gigabit adapter do not show up in ostinato port group on windows 7

These ethernet adapters are fully functional on windows.  Why does ostinato not see them?

See attachments

![network adapters](https://cloud.githubusercontent.com/assets/15792067/11079422/1fd5783a-87c1-11e5-82ae-60dcfb9a36bf.jpg)
![ostinato](https://cloud.githubusercontent.com/assets/15792067/11079426/287e9692-87c1-11e5-9054-55840a8073fc.jpg)

**Comment by pstavirs** [comment]
Duplicate discussion: https://groups.google.com/forum/#!topic/ostinato/kAgl48RfZo0

Please post at only one place - mailing list or issue tracker.
Typically, if you are sure it's a bug (or enhancement request), use
the issue tracker; if you are not sure and for everything else post on
the mailing list.

Use the mailing list for continuing the discussion/investigation. Closing this issue for now - will reopen if an actual issue is found
