### ISSUE TITLE
Add default extension when saving sessions or streams

### ISSUE THREAD

**Issue by ehlers** [pstavirs/ostinato#187]
When saving sessions or streams and the user doesn't enter an extension in the filename, it's saved without any extension. When opening a session or stream the file selector box doesn't show the just saved files. The user has to change the file type to "All files (*)" to see those files.

I suggest to add the default extension, when the user doesn't specifies one.

**Comment by pstavirs** [comment]
This was always the intention. And it works correctly on Windows. But not on Linux :(

Will investigate and fix suitably.

**Comment by pstavirs** [comment]
Here's the behaviour I see on Ubuntu Linux (with KDE) -

**Save Session**: The save dialog box has a checkbox at the bottom saying `automatically add extension` and it is checked by default - when you specify a file name without the extension, it is automatically added in the saved filename

**Open Session**: The open dialog box shows the filter as `Ostinato Session` instead of the full `Ostinato Session (*.ossn)`, but the shown filenames are as per the `*.ossn` pattern

**==> Session save/open doesn't seem to have a problem**

**Save Stream**: The save dialog box does **NOT** have a checkbox at the bottom saying `automatically add extension` - when you specify a file name without the extension, the saved filename does **NOT** have any extension.

**Open Stream**: Like open session, the open dialog box filters don't show the actual extensions but just `Ostinato`, `PCAP`, `PDML` etc., bu the shown filenames are as per the corresponding `*.ostm`, `*`, `*.pdml` patterns.

**==> Stream save/open has a problem with not automatically adding extension to the filename**

Can you confirm if you see something similar on TinyCore or something different? What Window Manager/Desktop Environment do you have on TinyCore (not sure if it makes a difference, but good to know)

**Comment by ehlers** [comment]
TinyCore uses flwm (http://flwm.sourceforge.net).

**Save Session**: No checkbox for automatically adding an extension. Specifying a filename without extension leads to a file without an extension.

**Open Session**: When the dialog starts, the filter shows the full `Ostinato Session (*.ossn)` and filters accordingly. When using the `All files (*)` filter, I see all files.

**Save Stream**: No checkbox for automatically adding an extension. Specifying a filename without extension leads to a file without an extension

**Open Session**: The filter shows the description + extension, e.g. `Ostinato (*.ostm)`.

So Save and Open are behaving the same for Session and Stream. On Save the extension is not added, on Open the filter shows the full description and extension. The Save and Open fileselector box are looking exactly the same.
![save_session](https://cloud.githubusercontent.com/assets/896406/15785988/7f51f734-29ba-11e6-9d0d-db9b1092f375.png)

**Comment by pstavirs** [comment]
@ehlers please verify and confirm if the fix works on tinycore

**Comment by ehlers** [comment]
Test with both save of sessions and streams. Works well, thank you.
