### ISSUE TITLE
Create DEB package for 'ostinato-server'

### ISSUE THREAD

**Issue by bdlamprecht** [pstavirs/ostinato#209]
There is an RPM package 'ostinato-server' that is used for running only "drone" part of the ostinato architecture.  It would be nice to have the same in a DEB package as well for `apt` package-manager based distributions (debian, ubuntu, etc).

**Comment by viniciusarcanjo** [comment]
+1. That'd be great. I'm also running debian based servers and I have to install tons of dependencies because of X11. 

Thanks!

**Comment by pstavirs** [comment]
Since version 0.9, Linux packages for all distros on [ostinato.org](http://ostinato.org/downloads) have two separate packages - `ostinato-agent` and `ostinato-controller` corresponding to the drone and the Ostinato GUI respectively. Users can choose to install either or both of the packages. Alternatively installing the included _meta_ package  `ostinato`, automatically installs both.
