### ISSUE TITLE
Timestamps on Pcap import

### ISSUE THREAD

**Issue by MorpheusDTA** [pstavirs/ostinato#218]
Using ostinato to generate traffic and replay pcap files, i have seen that timestamps are not repected when importing pcap files. The order is respected but timestamps may be changed when being sent (comparing the real pcap with a pcap recorded on the sender).
Could this be reviewed and corrected ? Thanks by advance.

**Comment by pstavirs** [comment]
Looking at the code, we do try to replicate the PCAP timing upto a usec resolution when importing PCAP files. There may be some variation during replay due to timing accuracy and CPU capacity issues. 

If there is a big variation between the original PCAP and the replay, please attach a sample original PCAP and a pcap capture of the replay for analysis.

**Comment by pstavirs** [comment]
@MorpheusDTA did you get a chance to check this?

**Comment by pstavirs** [comment]
No update from submitter. Closing.
