### ISSUE TITLE
Imported PCAP stream differs

### ISSUE THREAD

**Issue by b-ehlers** [pstavirs/ostinato#282]
Version: master branch, rev c8a4c3e
OS: macOS v10.13.6 (High Sierra) and Debian 10.0 (Buster)

After importing a PCAP stream (via Open Streams ...) the source and destination MAC address are set to zero. Therefore the user gets a warning:

![import_diff](https://user-images.githubusercontent.com/49040325/63638181-18c4a000-c685-11e9-900d-24aba7979d54.png)

Here the PCAP file (zipped): [STP.zip](https://github.com/pstavirs/ostinato/files/3537251/STP.zip)

I assume, that's because the new default for the MAC address mode is "Resolve". I suggest one of the following two options:
- do the comparison before setting the MAC addresses to zero. But then the user might not be aware of the MAC address change.
- set the MAC address mode to "Fixed" and keep the MAC addresses. But as the default MAC mode is "Resolve", the user might not look at the MAC layer and gets confused, when IP changes don't change the MAC address.

BTW: Ostinato gets really stable now, it gets more and more difficult to find any bugs. 😃

**Comment by pstavirs** [comment]
@b-ehlers Thank you for reporting yet another regression issue caused by recent changes. These bug reports are very timely, since I plan to make a new Ostinato release shortly.

Thank you also for your comments on the stability of Ostinato! :pray:

On this specific issue, as you rightly identified, changing the default mac mode from `fixed` to `resolve` caused the issue. I should have been more careful when changing the default since I made the same mistake in v0.9 when I changed the default num of packets in a stream from 1 to 10 breaking the pcap import.

Of the two solutions, setting the mode to `fixed` is the correct one because Ostinato's pcap import philosophy is to replicate the exact same packet as in the PCAP file. Even for checksums etc., Ostinato sets the _override checksum_ flag irrespective of the correctness of the checskum value in the pcap packet.

If user changes the IP address after import, he will have to set mac address manually (or change to resolve) and also uncheck the _override checksum_ field(s), so that the correct values get calculated.

Appreciate a confirmation on the fix.

**Comment by b-ehlers** [comment]
Just tested your fix, works fine.

I will do some last tests today, but I don't expect any further issues.

**Comment by b-ehlers** [comment]
Finished my tests on macOS and Debian 10, I don't use Windows. As expected I didn't find any issues, excellent job.

I concentrated my tests on stream statistics and the new features: hostdev and support of newer libpcap version (I used v1.8.1). But of course I re-tested also the previously tested features.

**Comment by pstavirs** [comment]
Thank a bunch @b-ehlers for all the testing and verfication! :pray:
