### ISSUE TITLE
Create stream takes long time with Python API

### ISSUE THREAD

**Issue by microflyer2001** [pstavirs/ostinato#284]
If I use the Windows GUI creating a stream of 100k TCP packets is almost instant after hitting the 'apply' button.
Using the Python API it takes over 5 minutes to create the same stream.

**Comment by pstavirs** [comment]
@microflyer2001: A few queries
* What version of the GUI and API are you using?
* When running the script using the API, is drone spewing out any logs?
* Please post your script snippet which is taking time

**Comment by microflyer2001** [comment]
I am using 0.9 Python API and also 0.9 on CentOS 7
Yes there are logs and I have attached a snip of the logs that occur during the long wait.
Also I have attached a snip of the Python API script in use at the time of the delay.
[ostinato-log.log.gz](https://github.com/pstavirs/ostinato/files/3670539/ostinato-log.log.gz)
[ostinato-snip.txt](https://github.com/pstavirs/ostinato/files/3670543/ostinato-snip.txt)
Thanks.

**Comment by pstavirs** [comment]
@microflyer2001 - when you run drone, can you redirect its stdout and stderr to `/dev/null` -
```
drone &> /dev/null
```

After doing this you will **not** see any output from drone. Re-run the script and let me know if it improves the time taken to create the stream.

**Comment by microflyer2001** [comment]
I have experimented with this in the past and never found a solution.
If I use your suggestion above the log seems to go into /var/log/messages sporadically?
and systemd-journal and rsyslogd are using lots of CPU
If I use the following then no logs are generated and the above processes are quiet but the stream still takes a very long time to be created
drone < /dev/null > /dev/null 2>&1 &

**Comment by microflyer2001** [comment]
OK. I have narrowed down this issue more.
It is the same issue regardless of if the stream is configured with Python API or Windows GUI or Linux GUI.
It is caused because I am incrementing the TCP sequence number for each packet using the variable fields.
I am using a count of 65535 for the sequence number.
For 6000 TCP packets it takes 15 seconds to configure the packets and 4 minutes for 100k packets.

The strange thing is that if I use a count of 2 then the time is negligible (even for 1M packets)
I cannot understand why using a smaller amount of sequence numbers would make it much faster because each packet still needs to be configured with a sequence number, why should it matter what that number is?

Is this something that can be fixed? I want to be able to identify each packet has reached the other side of a link.

**Comment by pstavirs** [comment]
@microflyer2001 : The time taken to create the packets depends only on the _sequence number count_ and not the _total number of packets_ sent out because Ostinato only creates the minimum number of _unique_ packets and reuses them. e.g. if you use a seq count of 2 and send 1M packets, Ostinato just creates two packets and keeps sending those two in a loop for a total of 1M packets. Let me know if this explanation is not clear or if you have any questions.

Regarding what can be done about it - in case some packets don't reach the other side, are you interested in knowing which _exact_ packets are dropped? Or is it enough to know _how many packets are dropped_? In case of the latter, you can use the [Stream Statistics](https://userguide.ostinato.org/StreamStats.html) feature and not use the variable fields feature.

**Comment by microflyer2001** [comment]
I understand now thanks.
I am afraid it is the former - I need to know exactly which packets have been dropped and even if not dropped I am comparing the data in the sent packet with the received packet at the bit level. 
So each packet needs to be unique so I guess I am stuck with the long time to create all the required packets.

**Comment by pstavirs** [comment]
@microflyer2001 : Yes, for now you'll have to live with the long time. I will try to address this as part of the [Turbo Transmit](https://mailchi.mp/ostinato/turbotransmit) add on.
