### ISSUE TITLE
creating streams with random MTU size causes the drone to be unresponsive

### ISSUE THREAD

**Issue by anubisg1** [pstavirs/ostinato#325]
UI running on windows
drone running on linux.

i'm using the session file attached. This configuration works and is applied without issues.

as soon as i change MTU from "fixed" to random between 64 and 9000 bytes,  and i apply, the drone becomes unresponsive and i'm left waiting for hours with no changes. if i start debug logs i get thousands of lines going on. i will try to collect the drone logs and attach them here. "drone -dp 7878 > log.txt" doesn't seem to be redirecting logs to file

[test.zip](https://github.com/pstavirs/ostinato/files/5402709/test.zip)

**Comment by anubisg1** [comment]
as promised, this is the log file
[session.zip](https://github.com/pstavirs/ostinato/files/5411008/session.zip)

the drone just spams the console and goes on and one seemingly forever. at some point (usually after 20 minutes) i just kill the process.

again, starting from the session attached, the only thing i do is to change MTU of the stream, from fixed 9000 to random between 64 and 9000

**Comment by pstavirs** [comment]
@anubisg1 There doesn't seem to be any streams configured in the attached sessions file (`test.zip`), only device groups. Can you double check?

Actually, session files are **not portable** i.e. I can't open your session file because I don't have the same port group IP addresses and port names. So I wrote a quick and dirty code to try and open your file, so there is a chance that there's a problem in that code, but I've double checked it and I don't think there is.

Can you repro the problem with just a simple stream? If you can, please save a stream file that I can open to reproduce the problem.

**Comment by anubisg1** [comment]
[LAB.zip](https://github.com/pstavirs/ostinato/files/5421822/LAB.zip)

Hello @pstavirs  i added the session and the stream file. thank you

**Comment by anubisg1** [comment]
thanks for fixing this
