### ISSUE TITLE
Support import/export of pcap-ng file format

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pstavirs/ostinato#83]
```
Wireshark has moved to pcap-ng as the default format and other tools will 
likely follow the lead and make the move.

Time for Ostinato to do so too.

```

Original issue reported on code.google.com by `pstav...@gmail.com` on 3 Nov 2012 at 5:52

**Comment by pstavirs** [comment]
Instead of adding native support for pcapng, a hacky way to do this is to use tshark to convert pcapng (or other formats supported by Wireshark, but not by Ostinato) into pcap and then import the pcap.

The downside of this approach is that we cannot use additional meta data available in the pcapng format.
